#!/usr/bin/env bash
# This is a script that will tranfer a file from client to server
if [ $# -lt 4 ]
then
  echo Usage: "0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "0-transfer_file" "100.25.158.115" "ubuntu":~
fi
