#!/usr/bin/env bash
# From the task 0
# Making the fix short and sweet, then configures to run on p80
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
eco "" > /run/nginx.pid
