#!/usr/bin/env bash
# A bash sript that displays the contents of the current directory in list format.
# It only displays part of the name after the first dash.

list=$(ls)
for i in $list; do
	echo "$i" | cut -d "-" -f2
done
