#!/usr/bin/env bash
# This script will then fix the bug in the web server
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
